# Generated by Django 5.2.7 on 2026-08-24 21:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaqs', '0003_alter_halaqa_res_teacher'),
        ('students', '0003_seed_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='date_birth',
            field=models.DateField(default=datetime.date(2010, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='halaqa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='halaqs.halaqa'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
