# Generated by Django 5.2.7 on 2025-10-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='res_halaqa',
        ),
    ]
