# Generated by Django 5.2.7 on 2025-10-20 09:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halaqs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_w_date', models.DateField(default=datetime.date.today)),
                ('amount', models.TextField()),
                ('compare_plan', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('halaqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halaqs.halaqa')),
            ],
        ),
    ]
