# Generated by Django 5.2.7 on 2025-10-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaqs', '0002_initial'),
        ('teachers', '0002_remove_teacher_res_halaqa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halaqa',
            name='res_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
    ]
