# Generated by Django 5.2.7 on 2026-08-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaqs', '0003_alter_halaqa_res_teacher'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='halaqa',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
